services:
  postgresdb:
    image: postgres:16-alpine   # or postgres:latest
    container_name: postgresdb
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - ols-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olsheets-backend
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - ols-network
    depends_on:
      - postgresdb
    # makes sure DB starts first
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
      - DB_POSTGRES_USERNAME=${POSTGRES_USER}
      - DB_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

networks:
  ols-network:
    driver: bridge

volumes:
  postgres_data:
