global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'olsheets-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'OLSHEETS'
          environment: 'production'

  - job_name: 'k6-metrics'
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['k6:6565']
        labels:
          application: 'K6'
          environment: 'test'

